services:
  nginx:
    build: .
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - server
    volumes:
      - ~/certs:/etc/nginx/ssl:ro

  server:
    build: ./server
    ports:
      - "3001:3001"